In [1]:
import pandas as pd
import numpy as np
from woe import *
from run_woe import run_WOE
from sklearn.model_selection import train_test_split

In [8]:
df = pd.read_excel('bank.xlsx')

y  = df['y'].apply(lambda x : 1 if x == 'yes' else 0)  # Convert to numeric
X = df.drop('y',axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


X_WOE_tranformed_train, X_WOE_tranformed_test, WOE, WOE_concise, WOE_no_gaps = run_WOE(X_train
, X_test
, y_train
, y_test
, max_cont_bin = 5
)

/Users/michaelcantrell/ds/repos/WOE-and-IV/run_woe.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  sub_WOE_df.sort_values('MIN_VALUE', inplace = True)
/Users/michaelcantrell/anaconda/lib/python3.5/site-packages/pandas/core/indexing.py:465: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [9]:
WOE

,VAR_NAME,MIN_VALUE,MAX_VALUE,COUNT,EVENT,EVENT_RATE,NONEVENT,NON_EVENT_RATE,DIST_EVENT,DIST_NON_EVENT,WOE,IV
0,age,19,33,846,107,0.126478,739,0.873522,0.294766,0.277194,0.061463,0.022943
1,age,34,39,672,73,0.108631,599,0.891369,0.201102,0.224681,-0.110870,0.022943
2,age,40,49,815,83,0.101840,732,0.898160,0.228650,0.274569,-0.183008,0.022943
3,age,50,87,696,100,0.143678,596,0.856322,0.275482,0.223556,0.208861,0.022943
4,job,admin.,admin.,306,42,0.137255,264,0.862745,0.115702,0.099025,0.155652,0.172137
5,job,blue-collar,blue-collar,618,47,0.076052,571,0.923948,0.129477,0.214179,-0.503310,0.172137
6,job,entrepreneur,entrepreneur,103,6,0.058252,97,0.941748,0.016529,0.036384,-0.789020,0.172137
7,job,housemaid,housemaid,76,11,0.144737,65,0.855263,0.030303,0.024381,0.217440,0.172137
8,job,management,management,659,92,0.139605,567,0.860395,0.253444,0.212678,0.175361,0.172137
9,job,retired,retired,168,41,0.244048,127,0.755952,0.112948,0.047637,0.863317,0.172137
10,job,self-employed,self-employed,131,16,0.122137,115,0.877863,0.044077,0.043136,0.021588,0.172137
11,job,services,services,285,26,0.091228,259,0.908772,0.071625,0.097149,-0.304800,0.172137
12,job,student,student,58,15,0.258621,43,0.741379,0.041322,0.016129,0.940782,0.172137
13,job,technician,technician,515,57,0.110680,458,0.889320,0.157025,0.171793,-0.089886,0.172137
14,job,unemployed,unemployed,82,5,0.060976,77,0.939024,0.013774,0.028882,-0.740436,0.172137
15,job,unknown,unknown,28,5,0.178571,23,0.821429,0.013774,0.008627,0.467875,0.172137
16,marital,divorced,divorced,337,48,0.142433,289,0.857567,0.132231,0.108402,0.198706,0.023756
17,marital,married,married,1887,202,0.107048,1685,0.892952,0.556474,0.632033,-0.127321,0.023756
18,marital,single,single,805,113,0.140373,692,0.859627,0.311295,0.259565,0.181734,0.023756
19,education,primary,primary,449,43,0.095768,406,0.904232,0.118457,0.152288,-0.251221,0.032412
20,education,secondary,secondary,1547,173,0.111829,1374,0.888171,0.476584,0.515379,-0.078258,0.032412
21,education,tertiary,tertiary,905,134,0.148066,771,0.851934,0.369146,0.289197,0.244083,0.032412
22,education,unknown,unknown,128,13,0.101562,115,0.898438,0.035813,0.043136,-0.186051,0.032412
23,default,no,no,2983,356,0.119343,2627,0.880657,0.980716,0.985371,-0.004735,0.001308
24,default,yes,yes,46,7,0.152174,39,0.847826,0.019284,0.014629,0.276280,0.001308
25,balance,-1746,70,759,63,0.083004,696,0.916996,0.173554,0.261065,-0.408283,0.072962
26,balance,71,454,756,78,0.103175,678,0.896825,0.214876,0.254314,-0.168507,0.072962
27,balance,455,1521,758,107,0.141161,651,0.858839,0.294766,0.244186,0.188251,0.072962
28,balance,1526,27359,756,115,0.152116,641,0.847884,0.316804,0.240435,0.275834,0.072962
29,housing,no,no,1339,214,0.159821,1125,0.840179,0.589532,0.421980,0.334369,0.113378
...,...,...,...,...,...,...,...,...,...,...,...,...
38,day,17,21,733,80,0.109141,653,0.890859,0.220386,0.244936,-0.105619,0.021830
39,day,22,31,756,91,0.120370,665,0.879630,0.250689,0.249437,0.005004,0.021830
40,month,apr,apr,191,41,0.214660,150,0.785340,0.112948,0.056264,0.696868,0.445272
41,month,aug,aug,430,48,0.111628,382,0.888372,0.132231,0.143286,-0.080288,0.445272
42,month,dec,dec,13,6,0.461538,7,0.538462,0.016529,0.002626,1.839781,0.445272
43,month,feb,feb,151,23,0.152318,128,0.847682,0.063361,0.048012,0.277396,0.445272
44,month,jan,jan,105,13,0.123810,92,0.876190,0.035813,0.034509,0.037092,0.445272
45,month,jul,jul,487,46,0.094456,441,0.905544,0.126722,0.165416,-0.266472,0.445272
46,month,jun,jun,347,41,0.118156,306,0.881844,0.112948,0.114779,-0.016081,0.445272
47,month,mar,mar,33,16,0.484848,17,0.515152,0.044077,0.006377,1.933307,0.445272
48,month,may,may,914,58,0.063457,856,0.936543,0.159780,0.321080,-0.697896,0.445272
49,month,nov,nov,266,30,0.112782,236,0.887218,0.082645,0.088522,-0.068703,0.445272
50,month,oct,oct,52,28,0.538462,24,0.461538,0.077135,0.009002,2.148082,0.445272
51,month,sep,sep,40,13,0.325000,27,0.675000,0.035813,0.010128,1.263044,0.445272
52,duration,5,104,764,15,0.019634,749,0.980366,0.041322,0.280945,-1.916757,1.182102
53,duration,105,187,756,31,0.041005,725,0.958995,0.085399,0.271943,-1.158253,1.182102
54,duration,188,336,756,88,0.116402,668,0.883598,0.242424,0.250563,-0.033020,1.182102
55,duration,337,2769,753,229,0.304117,524,0.695883,0.630854,0.196549,1.166162,1.182102
56,campaign,1,2,1994,263,0.131896,1731,0.868104,0.724518,0.649287,0.109631,0.032153
57,campaign,3,3,363,41,0.112948,322,0.887052,0.112948,0.120780,-0.067048,0.032153
58,campaign,4,50,672,59,0.087798,613,0.912202,0.162534,0.229932,-0.346896,0.032153
59,pdays,-1,-1,2485,234,0.094165,2251,0.905835,0.644628,0.844336,-0.269877,0.214942
60,pdays,1,1,1,1,1.000000,0,0.000000,0.002755,0.000000,0.000000,0.214942
61,pdays,2,761,543,128,0.235727,415,0.764273,0.352617,0.155664,0.817683,0.214942
62,previous,0,1,2671,267,0.099963,2404,0.900037,0.735537,0.901725,-0.203709,0.198370
63,previous,2,24,358,96,0.268156,262,0.731844,0.264463,0.098275,0.989935,0.198370
64,poutcome,failure,failure,326,43,0.131902,283,0.868098,0.118457,0.106152,0.109685,0.476572
65,poutcome,other,other,130,28,0.215385,102,0.784615,0.077135,0.038260,0.701163,0.476572
66,poutcome,success,success,88,58,0.659091,30,0.340909,0.159780,0.011253,2.653177,0.476572
67,poutcome,unknown,unknown,2485,234,0.094165,2251,0.905835,0.644628,0.844336,-0.269877,0.476572

In [10]:
X_WOE_tranformed_test.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
2398,0.208861,-0.789020,-0.127321,-0.078258,0.276280,-0.408283,0.334369,-0.486335,0.245632,0.005004,-0.266472,-1.158253,-0.346896,-0.269877,-0.203709,-0.269877
800,0.208861,0.175361,-0.127321,0.244083,-0.004735,0.275834,0.334369,0.071448,0.245632,-0.140773,-0.080288,1.166162,0.109631,0.817683,0.989935,0.701163
2288,0.208861,-0.089886,-0.127321,-0.078258,-0.004735,0.188251,0.334369,0.071448,0.245632,-0.140773,-0.080288,-1.158253,-0.067048,-0.269877,-0.203709,-0.269877
2344,-0.110870,0.175361,-0.127321,0.244083,-0.004735,-0.408283,-0.342309,0.071448,-0.950507,-0.140773,-0.016081,-0.033020,-0.346896,-0.269877,-0.203709,-0.269877
3615,0.061463,0.155652,0.181734,-0.078258,-0.004735,0.188251,0.334369,0.071448,0.245632,-0.140773,0.277396,1.166162,0.109631,-0.269877,-0.203709,-0.269877

In [11]:
X_test.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
2398,51,entrepreneur,married,secondary,yes,-2082,no,yes,cellular,28,jul,123,6,-1,0,unknown
800,50,management,married,tertiary,no,2881,no,no,cellular,5,aug,510,2,2,5,other
2288,50,technician,married,secondary,no,1412,no,no,cellular,6,aug,131,3,-1,0,unknown
2344,37,management,married,tertiary,no,0,yes,no,unknown,3,jun,247,13,-1,0,unknown
3615,31,admin.,single,secondary,no,757,no,no,cellular,3,feb,343,2,-1,0,unknown

In [13]:
WOE[WOE.VAR_NAME.isin(['age', 'job', 'marital', 'education', 'default', 'balance'])]

,VAR_NAME,MIN_VALUE,MAX_VALUE,COUNT,EVENT,EVENT_RATE,NONEVENT,NON_EVENT_RATE,DIST_EVENT,DIST_NON_EVENT,WOE,IV
0,age,19,33,846,107,0.126478,739,0.873522,0.294766,0.277194,0.061463,0.022943
1,age,34,39,672,73,0.108631,599,0.891369,0.201102,0.224681,-0.110870,0.022943
2,age,40,49,815,83,0.101840,732,0.898160,0.228650,0.274569,-0.183008,0.022943
3,age,50,87,696,100,0.143678,596,0.856322,0.275482,0.223556,0.208861,0.022943
4,job,admin.,admin.,306,42,0.137255,264,0.862745,0.115702,0.099025,0.155652,0.172137
5,job,blue-collar,blue-collar,618,47,0.076052,571,0.923948,0.129477,0.214179,-0.503310,0.172137
6,job,entrepreneur,entrepreneur,103,6,0.058252,97,0.941748,0.016529,0.036384,-0.789020,0.172137
7,job,housemaid,housemaid,76,11,0.144737,65,0.855263,0.030303,0.024381,0.217440,0.172137
8,job,management,management,659,92,0.139605,567,0.860395,0.253444,0.212678,0.175361,0.172137
9,job,retired,retired,168,41,0.244048,127,0.755952,0.112948,0.047637,0.863317,0.172137
10,job,self-employed,self-employed,131,16,0.122137,115,0.877863,0.044077,0.043136,0.021588,0.172137
11,job,services,services,285,26,0.091228,259,0.908772,0.071625,0.097149,-0.304800,0.172137
12,job,student,student,58,15,0.258621,43,0.741379,0.041322,0.016129,0.940782,0.172137
13,job,technician,technician,515,57,0.110680,458,0.889320,0.157025,0.171793,-0.089886,0.172137
14,job,unemployed,unemployed,82,5,0.060976,77,0.939024,0.013774,0.028882,-0.740436,0.172137
15,job,unknown,unknown,28,5,0.178571,23,0.821429,0.013774,0.008627,0.467875,0.172137
16,marital,divorced,divorced,337,48,0.142433,289,0.857567,0.132231,0.108402,0.198706,0.023756
17,marital,married,married,1887,202,0.107048,1685,0.892952,0.556474,0.632033,-0.127321,0.023756
18,marital,single,single,805,113,0.140373,692,0.859627,0.311295,0.259565,0.181734,0.023756
19,education,primary,primary,449,43,0.095768,406,0.904232,0.118457,0.152288,-0.251221,0.032412
20,education,secondary,secondary,1547,173,0.111829,1374,0.888171,0.476584,0.515379,-0.078258,0.032412
21,education,tertiary,tertiary,905,134,0.148066,771,0.851934,0.369146,0.289197,0.244083,0.032412
22,education,unknown,unknown,128,13,0.101562,115,0.898438,0.035813,0.043136,-0.186051,0.032412
23,default,no,no,2983,356,0.119343,2627,0.880657,0.980716,0.985371,-0.004735,0.001308
24,default,yes,yes,46,7,0.152174,39,0.847826,0.019284,0.014629,0.276280,0.001308
25,balance,-1746,70,759,63,0.083004,696,0.916996,0.173554,0.261065,-0.408283,0.072962
26,balance,71,454,756,78,0.103175,678,0.896825,0.214876,0.254314,-0.168507,0.072962
27,balance,455,1521,758,107,0.141161,651,0.858839,0.294766,0.244186,0.188251,0.072962
28,balance,1526,27359,756,115,0.152116,641,0.847884,0.316804,0.240435,0.275834,0.072962